export const GET_ALL_USER_INFO_REQUEST = "user/GET_ALL_USER_INFO_REQUEST";
export const GET_ALL_USER_INFO_REQUEST_SUCCESS = "user/GET_ALL_USER_INFO_REQUEST_SUCCESS";
export const GET_ALL_USER_INFO_REQUEST_FAILURE = "user/GET_ALL_USER_INFO_REQUEST_FAILURE";